<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>disable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="MediatR" Version="14.1.0" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="8.0.25" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.25">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="System.Data.SQLite.Core" Version="1.0.119" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\CORE\CORE.csproj" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="Properties\" />
    </ItemGroup>

</Project>